'use strict';
const STAGES=[
 {year:'325م',name:'مجمع نيقية',kind:'مجمع مسكوني',heretic:'أريوس',defender:'القديس أثناسيوس',claim:'قال أريوس إن الابن مخلوق عظيم، لكنه ليس إلهًا حقيقيًا مثل الآب.',truth:'دافعت الكنيسة عن ألوهية الابن: «إله حق من إله حق، مولود غير مخلوق، مساوٍ للآب في الجوهر».',qs:[['مَن صاحب التعليم الذي واجهه مجمع نيقية؟',['أريوس','نسطور','مقدونيوس'],0,'أريوس هو الذي أنكر ألوهية الابن الكاملة.'],['مَن كان أبرز المدافعين عن الإيمان؟',['القديس أثناسيوس','أوطاخي','مار مرقس'],0,'القديس أثناسيوس دافع بقوة عن ألوهية الابن.'],['ما التعبير الذي ثبّته المجمع؟',['مساوٍ للآب في الجوهر','أقل من الآب','إنسان فقط'],0,'هذا التعبير يحفظ حقيقة ألوهية المسيح.']]},
 {year:'381م',name:'مجمع القسطنطينية',kind:'مجمع مسكوني',heretic:'مقدونيوس',defender:'غريغوريوس اللاهوتي',claim:'أنكر مقدونيوس لاهوت الروح القدس، واعتبره قوة أو مخلوقًا.',truth:'أكملت الكنيسة قانون الإيمان وأعلنت أن الروح القدس هو الرب المحيي، المنبثق من الآب.',qs:[['ماذا أنكر مقدونيوس؟',['لاهوت الروح القدس','قيامة المسيح','التجسد'],0,'كان الخلاف حول لاهوت الروح القدس.'],['مَن أبرز المدافعين؟',['غريغوريوس اللاهوتي','أريوس','نسطور'],0,'شرح غريغوريوس لاهوت الروح القدس بوضوح.'],['ماذا وصف القانون الروح القدس؟',['الرب المحيي','ملاك عظيم','رمز فقط'],0,'نؤمن بالروح القدس، الرب المحيي.']]},
 {year:'431م',name:'مجمع أفسس',kind:'مجمع مسكوني',heretic:'نسطور',defender:'القديس كيرلس الكبير',claim:'فصل نسطور بين لاهوت المسيح وناسوته كأنهما شخصان، ورفض لقب والدة الإله.',truth:'دافع القديس كيرلس عن وحدة شخص المسيح: الكلمة المتجسد واحد، والعذراء والدة الإله.',qs:[['مَن قاد الدفاع في أفسس؟',['القديس كيرلس','مقدونيوس','أريوس'],0,'قاد القديس كيرلس الكبير الدفاع عن وحدة شخص المسيح.'],['ما اللقب الذي أكده المجمع؟',['والدة الإله','والدة إنسان فقط','ملكة سياسية'],0,'اللقب يحفظ حقيقة أن المولود منها هو الله الكلمة المتجسد.'],['المسيح بحسب إيمان الكنيسة هو…',['شخص واحد متجسد','شخصان منفصلان','إنسان فقط'],0,'المسيح واحد، كامل في لاهوته وكامل في ناسوته.']]},
 {year:'451م',name:'صخرة خلقيدونية',kind:'طريق انقسام',heretic:'صياغات ملتبسة',defender:'الكنيسة القبطية',claim:'ظهرت صخرة خلاف كبيرة حول التعبير عن اتحاد اللاهوت والناسوت، وتفرع طريق موازٍ.',truth:'ظل المسافرون على الطريق الذي تسلّموه: طبيعة واحدة لله الكلمة المتجسد، بلا اختلاط ولا تغيير.',branch:true,qs:[['هل اختلط اللاهوت بالناسوت؟',['لا، اتحدا بلا اختلاط','نعم تمامًا','لم يوجد ناسوت'],0,'الاتحاد حقيقي بلا اختلاط ولا تغيير.'],['ماذا حدث للطريق تاريخيًا؟',['ظهر انقسام','انتهى الإيمان','اختفت الكنيسة'],0,'ظهر طريق موازٍ، لكن الطريق الأصلي استمر.'],['كيف نتعامل مع المختلفين؟',['محبة وأمانة','سخرية','تجاهل المعرفة'],0,'المحبة لا تلغي الأمانة، والأمانة لا تلغي المحبة.']]},
 {year:'1054م',name:'الانقسام الكبير',kind:'طريق انقسام',heretic:'خلاف الشرق والغرب',defender:'شهود التقليد',claim:'تراكمت خلافات لاهوتية وكنسية وسياسية، فتباعد طريقا الشرق والغرب.',truth:'المسافر يرى الفرع بوضوح، لكنه يواصل الطريق الرسولي المستقيم بمحبة للجميع.',branch:true,qs:[['متى وقع الانقسام الكبير؟',['1054م','325م','431م'],0,'يرتبط الانقسام الكبير تقليديًا بسنة 1054م.'],['هل كان السبب واحدًا بسيطًا؟',['لا، تراكمت أسباب كثيرة','نعم، سبب واحد','لم يقع انقسام'],0,'تراكمت عوامل لاهوتية وكنسية وسياسية.'],['موقفنا الصحيح هو…',['معرفة ومحبة','إدانة الأشخاص','نسيان التاريخ'],0,'نتعلم التاريخ بلا تعالٍ أو إدانة.']]},
 {year:'القرن 16',name:'تفرعات الإصلاح',kind:'طرق متعددة',heretic:'تفسيرات متفرعة',defender:'أمانة الكنيسة',claim:'تكاثرت طرق جديدة، وكل طريق تبعه طرق أخرى، حتى امتلأ الأفق بالتفرعات.',truth:'رغم كثرة الفروع، لم ينقطع الطريق الأصلي الذي تسلّمته الكنيسة من الرسل.',branch:true,qs:[['ماذا حدث في القرن السادس عشر؟',['كثرت التفرعات','انعقد نيقية','بدأت المسيحية'],0,'ظهرت حركات الإصلاح ثم تفرعات كثيرة.'],['هل انقطع الطريق الأصلي؟',['لا','نعم','لا نعرف'],0,'استمر التقليد الرسولي عبر الأجيال.'],['ما مسؤوليتنا اليوم؟',['نحفظ الإيمان ونعيشه بمحبة','نهاجم الجميع','نكتفي بالأسماء'],0,'المطلوب معرفة حيّة وأمانة مملوءة بالمحبة.']]}
];
const $=s=>document.querySelector(s),canvas=$('#world'),ctx=canvas.getContext('2d');
const bg=new Image(),roadTex=new Image(),travelerSprite=new Image(),councilSprite=new Image();
bg.src='assets/ancient-valley.png';roadTex.src='assets/stone-road.png';travelerSprite.src='assets/travelers.png';councilSprite.src='assets/council-pair.png';
let W=0,H=0,dpr=1,state='welcome',distance=0,speed=0,lane=0,laneVelocity=0,stageIndex=0,qIndex=0,stageScore=0,total=0,last=performance.now(),sound=true;
const input={forward:false,left:false,right:false};
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function show(id){document.querySelectorAll('.overlay').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}
function tone(freq=500){if(!sound)return;try{const a=new(window.AudioContext||webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.08,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.25);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.26)}catch(e){}}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function drawBackground(){if(bg.complete)ctx.drawImage(bg,0,0,bg.width,bg.height,0,0,W,H);else{const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#4b91c5');g.addColorStop(1,'#d69a4d');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}ctx.fillStyle='rgba(238,185,91,.10)';ctx.fillRect(0,0,W,H)}
function roadPoint(t,offset=0){const horizon=H*.43,y=horizon+(H-horizon)*Math.pow(t,1.75),center=W/2+Math.sin(distance*.0013+t*2.3)*W*.045,half=lerp(W*.018,W*.43,t);return{x:center+half*offset,y,half}}
function lerp(a,b,t){return a+(b-a)*t}
function texturedQuad(p1,p2,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.beginPath();ctx.moveTo(p1.x-p1.half,p1.y);ctx.lineTo(p1.x+p1.half,p1.y);ctx.lineTo(p2.x+p2.half,p2.y);ctx.lineTo(p2.x-p2.half,p2.y);ctx.closePath();ctx.clip();const top=Math.min(p1.y,p2.y),height=Math.abs(p2.y-p1.y)+2,sy=Math.floor((distance*18+p1.y*2)%roadTex.height);if(roadTex.complete&&roadTex.naturalWidth){ctx.drawImage(roadTex,0,sy,roadTex.width,Math.min(90,roadTex.height-sy),Math.min(p1.x-p1.half,p2.x-p2.half),top,Math.max(p1.half,p2.half)*2,height)}else{ctx.fillStyle='#9c8769';ctx.fillRect(0,top,W,height)}ctx.restore();ctx.strokeStyle='rgba(50,35,20,.48)';ctx.lineWidth=Math.max(1,p2.half*.012);ctx.beginPath();ctx.moveTo(p1.x-p1.half,p1.y);ctx.lineTo(p2.x-p2.half,p2.y);ctx.moveTo(p1.x+p1.half,p1.y);ctx.lineTo(p2.x+p2.half,p2.y);ctx.stroke()}
function drawRoad(){const rows=54;for(let i=0;i<rows;i++){const t1=i/rows,t2=(i+1)/rows;texturedQuad(roadPoint(t1),roadPoint(t2))}const shine=ctx.createLinearGradient(W*.3,0,W*.7,0);shine.addColorStop(0,'rgba(255,232,174,0)');shine.addColorStop(.5,'rgba(255,235,175,.17)');shine.addColorStop(1,'rgba(255,232,174,0)');ctx.fillStyle=shine;const a=roadPoint(.04),b=roadPoint(1);ctx.beginPath();ctx.moveTo(a.x-a.half,a.y);ctx.lineTo(a.x+a.half,a.y);ctx.lineTo(b.x+b.half,b.y);ctx.lineTo(b.x-b.half,b.y);ctx.fill()}
function drawBranch(){if(stageIndex<3)return;const visibility=Math.min(1,(distance%100)/35+.2),dir=stageIndex%2?1:-1;ctx.save();ctx.globalAlpha=visibility;for(let i=0;i<26;i++){const t1=.12+i/34,t2=.12+(i+1)/34,p1=roadPoint(t1),p2=roadPoint(t2),spread1=(t1-.12)*W*.47*dir,spread2=(t2-.12)*W*.47*dir;p1.x+=spread1;p2.x+=spread2;p1.half*=.34;p2.half*=.34;texturedQuad(p1,p2,.82)}const r=roadPoint(.55);drawRock(r.x+dir*W*.22,r.y,Math.max(24,W*.045));ctx.restore()}
function drawRock(x,y,s){ctx.fillStyle='#5e4d43';ctx.beginPath();ctx.moveTo(x-s,y);ctx.lineTo(x-s*.7,y-s*.8);ctx.lineTo(x,y-s*1.15);ctx.lineTo(x+s,y-s*.3);ctx.lineTo(x+s*.8,y);ctx.fill();ctx.strokeStyle='#382a25';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-s*.2,y-s*.8);ctx.lineTo(x+s*.2,y-s*.35);ctx.stroke()}
function drawGate(){const progress=(distance%100)/100;if(progress<.28)return;const t=Math.min(.73,.12+(progress-.28)*.9),p=roadPoint(t),s=Math.max(18,p.half*.24);ctx.fillStyle='#80694c';ctx.fillRect(p.x-p.half*1.08,p.y-s*3,s*.55,s*3);ctx.fillRect(p.x+p.half*1.08-s*.55,p.y-s*3,s*.55,s*3);ctx.fillStyle='#c8ae7e';ctx.fillRect(p.x-p.half*1.13,p.y-s*3.2,s*.75,s*.3);ctx.fillRect(p.x+p.half*1.13-s*.75,p.y-s*3.2,s*.75,s*.3);if(stageIndex<3){ctx.fillStyle='#674422';ctx.fillRect(p.x-p.half,p.y-s*2.55,p.half*2,s*.25)}ctx.fillStyle='rgba(30,18,7,.84)';roundRect(p.x-s*1.55,p.y-s*4.25,s*3.1,s*.75,s*.12);ctx.fillStyle='#ffe5a8';ctx.font=`900 ${Math.max(10,s*.36)}px Cairo`;ctx.textAlign='center';ctx.fillText(STAGES[Math.min(stageIndex,5)].year,p.x,p.y-s*3.75)}
function drawFigure(x,y,h,colors,bob=0){ctx.save();ctx.translate(x,y+bob);ctx.fillStyle='rgba(30,20,10,.32)';ctx.beginPath();ctx.ellipse(0,0,h*.24,h*.07,0,0,7);ctx.fill();ctx.fillStyle=colors.robe;ctx.beginPath();ctx.moveTo(-h*.14,0);ctx.quadraticCurveTo(-h*.18,-h*.44,0,-h*.62);ctx.quadraticCurveTo(h*.18,-h*.44,h*.14,0);ctx.fill();ctx.fillStyle='#dcb487';ctx.beginPath();ctx.arc(0,-h*.7,h*.08,0,7);ctx.fill();ctx.fillStyle=colors.scarf;ctx.beginPath();ctx.arc(0,-h*.73,h*.095,Math.PI,0);ctx.lineTo(h*.1,-h*.53);ctx.lineTo(-h*.1,-h*.53);ctx.fill();ctx.restore()}
function drawTravelers(time){const p=roadPoint(.94,lane),height=Math.min(H*.49,W*.63),width=height*(travelerSprite.width/travelerSprite.height||.667),walk=speed>.15?Math.sin(distance*2.2)*5:0;ctx.fillStyle='rgba(40,24,8,.34)';ctx.beginPath();ctx.ellipse(p.x,p.y+5,width*.42,height*.045,0,0,7);ctx.fill();if(travelerSprite.complete&&travelerSprite.naturalWidth)ctx.drawImage(travelerSprite,p.x-width/2,p.y-height+walk,width,height);else drawFigure(p.x,p.y,height,{robe:'#eee3ca',scarf:'#c89531'},walk)}
function drawMilestonePeople(){const pr=(distance%100)/100;if(pr<.4)return;const p=roadPoint(.58),st=STAGES[Math.min(stageIndex,5)],fade=Math.min(1,(pr-.4)*5),w=Math.min(W*.58,p.half*3.5),h=w/(councilSprite.width/councilSprite.height||1.5);ctx.save();ctx.globalAlpha=fade;if(councilSprite.complete&&councilSprite.naturalWidth)ctx.drawImage(councilSprite,p.x-w/2,p.y-h,w,h);else{drawFigure(p.x-p.half*1.38,p.y,h*.7,{robe:'#792f2c',scarf:'#3c2923'});drawFigure(p.x+p.half*1.38,p.y,h*.7,{robe:'#315e7b',scarf:'#e4d2a7'})}ctx.fillStyle='rgba(25,16,7,.82)';ctx.font=`700 ${Math.max(9,w*.045)}px Cairo`;ctx.textAlign='center';ctx.fillText(st.heretic,p.x-w*.255,p.y+14);ctx.fillText(st.defender,p.x+w*.255,p.y+14);ctx.restore()}
function updateMotion(dt){if(state!=='play'){speed=Math.max(0,speed-dt*2.8);return}const target=input.forward?1:0;speed+=Math.sign(target-speed)*Math.min(Math.abs(target-speed),dt*(target?1.75:2.7));const steer=(input.right?1:0)-(input.left?1:0);laneVelocity+=steer*dt*2.3;laneVelocity*=Math.pow(.055,dt);laneVelocity=Math.max(-.72,Math.min(.72,laneVelocity));lane+=laneVelocity*dt;lane=Math.max(-.52,Math.min(.52,lane));distance+=speed*dt*8.8;if(distance>=(stageIndex+1)*100-3){speed=0;input.forward=false;distance=(stageIndex+1)*100-3;openStage()}}
function render(now){const dt=Math.min(.04,(now-last)/1000||.016);last=now;updateMotion(dt);drawBackground();drawRoad();drawBranch();drawGate();drawMilestonePeople();drawTravelers(now);requestAnimationFrame(render)}requestAnimationFrame(render);
function updateHud(){const pct=Math.min(100,distance/(STAGES.length*100)*100);$('#progressFill').style.width=pct+'%';$('#progressText').textContent=stageIndex<STAGES.length?STAGES[stageIndex].name:'نهاية الطريق';$('#score').textContent=total;if(stageIndex<STAGES.length){$('#stageYear').textContent=STAGES[stageIndex].year;$('#stageName').textContent=STAGES[stageIndex].name}}
setInterval(updateHud,100);
function openStage(){if(state!=='play')return;state='story';const s=STAGES[stageIndex];$('#storyBadge').textContent=s.kind;$('#storyTitle').textContent=s.year+' — '+s.name;$('#storyText').textContent=s.claim+'\n\n'+s.truth;$('#figures').innerHTML=figureCard(s.heretic,'صاحب التعليم المخالف','heretic','#812f2d','#382621')+figureCard(s.defender,'المدافع عن الإيمان','defender','#315f7c','#e6d1a6');show('#story');tone(280)}
function figureCard(name,role,type,robe,hair){return `<div class="figure-card ${type}"><div class="avatar" style="--robe:${robe};--hair:${hair}"></div><small>${role}</small><b>${name}</b></div>`}
function beginQuiz(){qIndex=0;stageScore=0;show('#quiz');renderQuestion()}
function renderQuestion(){const s=STAGES[stageIndex],q=s.qs[qIndex];$('#quizCounter').textContent=`سؤال ${qIndex+1} من ${s.qs.length}`;$('#quizStars').textContent='★'.repeat(stageScore)+'☆'.repeat(3-stageScore);$('#question').textContent=q[0];$('#answers').innerHTML='';$('#explanation').classList.add('hidden');$('#nextQuestion').classList.add('hidden');q[1].forEach((text,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=text;b.onclick=()=>answer(i,b);$('#answers').appendChild(b)})}
function answer(i,btn){const q=STAGES[stageIndex].qs[qIndex],buttons=[...document.querySelectorAll('.answer')];buttons.forEach(b=>b.disabled=true);if(i===q[2]){btn.classList.add('correct');stageScore++;tone(720)}else{btn.classList.add('wrong');buttons[q[2]].classList.add('correct');tone(150)}$('#quizStars').textContent='★'.repeat(stageScore)+'☆'.repeat(3-stageScore);$('#explanation').textContent=q[3];$('#explanation').classList.remove('hidden');$('#nextQuestion').classList.remove('hidden');$('#nextQuestion').innerHTML=qIndex===2?'واصل الرحلة <span>←</span>':'السؤال التالي <span>←</span>'}
function nextQuestion(){if(qIndex<2){qIndex++;renderQuestion();return}total+=stageScore;stageIndex++;if(stageIndex>=STAGES.length){finishGame();return}distance=stageIndex*100;state='play';document.querySelectorAll('.overlay').forEach(x=>x.classList.add('hidden'));tone(520)}
function finishGame(){state='ending';$('#finalStars').textContent='★'.repeat(Math.max(1,Math.round(total/3)))+'☆'.repeat(Math.max(0,6-Math.round(total/3)));$('#finalMessage').textContent=`جمعت ${total} من 18 نجمة. الطريق المستقيم لم ينقطع، وأصبحت تعرف لماذا حفظته الكنيسة عبر الأجيال.`;show('#ending');tone(880)}
function setInput(name,value){input[name]=value}
$('#startBtn').onclick=()=>{state='play';show('#welcome');$('#welcome').classList.add('hidden');$('#hud').classList.remove('hidden');$('#controls').classList.remove('hidden');$('#stageLabel').classList.remove('hidden');tone(520)};
$('#storyNext').onclick=beginQuiz;$('#storyClose').onclick=()=>{};$('#nextQuestion').onclick=nextQuestion;$('#restartBtn').onclick=()=>location.reload();$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'♫':'×'};
document.querySelectorAll('[data-move]').forEach(b=>{const key=b.dataset.move;b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);setInput(key,true)};b.onpointerup=b.onpointercancel=()=>setInput(key,false)});
$('#walkBtn').onpointerdown=e=>{e.preventDefault();$('#walkBtn').setPointerCapture(e.pointerId);setInput('forward',true)};$('#walkBtn').onpointerup=$('#walkBtn').onpointercancel=()=>setInput('forward',false);
addEventListener('keydown',e=>{if(['ArrowLeft','KeyA'].includes(e.code))input.left=true;if(['ArrowRight','KeyD'].includes(e.code))input.right=true;if(['ArrowUp','KeyW','Space'].includes(e.code)){input.forward=true;e.preventDefault()}});
addEventListener('keyup',e=>{if(['ArrowLeft','KeyA'].includes(e.code))input.left=false;if(['ArrowRight','KeyD'].includes(e.code))input.right=false;if(['ArrowUp','KeyW','Space'].includes(e.code))input.forward=false});
