import * as THREE from 'three';

const $=s=>document.querySelector(s), clamp=THREE.MathUtils.clamp, lerp=THREE.MathUtils.lerp;
const SAVE='neonRailRush.v1';
const defaults={coins:0,best:0,totalDistance:0,missions:{coins:0,jumps:0,rolls:0,distance:0,powers:0,mult:0},claimed:{},upgrades:{magnet:0,flight:0,jump:0,boost:0,shield:0},skin:0,music:true,sfx:true};
let save; try{save={...defaults,...JSON.parse(localStorage.getItem(SAVE)||'{}')};save.missions={...defaults.missions,...save.missions};save.upgrades={...defaults.upgrades,...save.upgrades};}catch{save=structuredClone(defaults)}
const persist=()=>localStorage.setItem(SAVE,JSON.stringify(save));

const scene=new THREE.Scene(); scene.background=new THREE.Color(0x171a4b); scene.fog=new THREE.Fog(0x171a4b,38,145);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,250);
const renderer=new THREE.WebGLRenderer({antialias:devicePixelRatio<2,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;$('#game').append(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xb5d8ff,0x35204c,2.2));const sun=new THREE.DirectionalLight(0xffe2bd,2.6);sun.position.set(-18,30,12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-22;sun.shadow.camera.right=22;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-10;scene.add(sun);
const mats={track:new THREE.MeshStandardMaterial({color:0x2e3751,roughness:.8}),rail:new THREE.MeshStandardMaterial({color:0xb9d4dc,metalness:.8,roughness:.25}),road:new THREE.MeshStandardMaterial({color:0x151936}),cyan:new THREE.MeshStandardMaterial({color:0x1be7ff,emissive:0x087a88,emissiveIntensity:1}),pink:new THREE.MeshStandardMaterial({color:0xff3cac,emissive:0x6b0d48,emissiveIntensity:.7}),yellow:new THREE.MeshStandardMaterial({color:0xffd43b,emissive:0x8c5d00,emissiveIntensity:.7}),orange:new THREE.MeshStandardMaterial({color:0xff633e}),dark:new THREE.MeshStandardMaterial({color:0x171b35}),glass:new THREE.MeshStandardMaterial({color:0x4ad7ff,emissive:0x06394e,metalness:.4,roughness:.15}),green:new THREE.MeshStandardMaterial({color:0x4be08a}),white:new THREE.MeshStandardMaterial({color:0xf5f4ff})};
const geo={box:new THREE.BoxGeometry(1,1,1),sphere:new THREE.SphereGeometry(1,12,8),cyl:new THREE.CylinderGeometry(1,1,1,12),coin:new THREE.CylinderGeometry(.34,.34,.09,16),torus:new THREE.TorusGeometry(.48,.1,7,16)};
const mesh=(g,m,p,s)=>{let x=new THREE.Mesh(g,m);x.position.set(...p);if(s)x.scale.set(...s);return x};

// Audio is synthesized so the project has no copyrighted or network audio dependency.
let ac,master,musicTimer;function audio(){if(ac)return;ac=new AudioContext();master=ac.createGain();master.gain.value=.18;master.connect(ac.destination)}
function beep(freq=440,d=.08,type='sine',vol=.25,slide=0){if(!save.sfx)return;audio();let o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,ac.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(slide,ac.currentTime+d);g.gain.setValueAtTime(vol,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+d);o.connect(g).connect(master);o.start();o.stop(ac.currentTime+d)}
function music(on){clearInterval(musicTimer);if(!on||!save.music)return;audio();let n=0,notes=[110,164,196,147,123,185,220,164];musicTimer=setInterval(()=>{let o=ac.createOscillator(),g=ac.createGain();o.type='triangle';o.frequency.value=notes[n++%notes.length];g.gain.setValueAtTime(.08,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.22);o.connect(g).connect(master);o.start();o.stop(ac.currentTime+.23)},250)}

const world=new THREE.Group();scene.add(world);const segments=[];const SEG=24,COUNT=8;
function building(x,z,h,color){const g=new THREE.Group();let b=mesh(geo.box,new THREE.MeshStandardMaterial({color,roughness:.75}),[x,h/2-1,z],[5+Math.random()*5,h,6+Math.random()*5]);g.add(b);for(let y=1;y<h-1;y+=2.4){for(let xx=-1;xx<=1;xx+=2){let w=mesh(geo.box,Math.random()>.35?mats.yellow:mats.cyan,[x+xx*1.2,y,z+(x<0?3.05:-3.05)],[.65,.5,.06]);g.add(w)}}return g}
function makeSegment(i){const g=new THREE.Group();g.userData.index=i;let bed=mesh(geo.box,mats.track,[0,-.65,0],[12,1,SEG]);g.add(bed);[-3,0,3].forEach(x=>{g.add(mesh(geo.box,mats.road,[x,-.08,0],[2.55,.18,SEG]));g.add(mesh(geo.box,mats.rail,[x-.82,.07,0],[.09,.08,SEG]));g.add(mesh(geo.box,mats.rail,[x+.82,.07,0],[.09,.08,SEG]));for(let z=-SEG/2;z<SEG/2;z+=1.7)g.add(mesh(geo.box,mats.dark,[x,.04,z],[2,.07,.16]))});
  [-1,1].forEach(side=>{g.add(mesh(geo.box,mats.dark,[side*7,.1,0],[2.2,.4,SEG]));if(i%2===0){for(let z=-10;z<11;z+=6){let pole=mesh(geo.cyl,mats.rail,[side*6.4,2,z],[.08,4,.08]);g.add(pole);g.add(mesh(geo.box,mats.cyan,[side*6.4,4,z],[.8,.18,.2]))}}g.add(building(side*(12+Math.random()*5),0,7+Math.random()*15,[0x30457a,0x623c81,0x315c69][i%3]))});
  if(i%3===1){let arch=mesh(geo.box,mats.pink,[0,7,0],[15,.45,.6]);g.add(arch);[-6,6].forEach(x=>g.add(mesh(geo.box,mats.dark,[x,3.5,0],[.5,7,.6])))}
  if(i%4===2){let sign=mesh(geo.box,mats.yellow,[7,5,-4],[.2,2.5,5]);g.add(sign)}
  world.add(g);segments.push(g);return g}
for(let i=0;i<COUNT;i++){let s=makeSegment(i);s.position.z=-i*SEG}

// Original articulated runner built from reusable low-poly parts.
const runner=new THREE.Group();scene.add(runner);const skinM=new THREE.MeshStandardMaterial({color:0xbf704b}),hairM=new THREE.MeshStandardMaterial({color:0x10142e});
const body=mesh(geo.box,mats.pink,[0,1.45,0],[.82,1.08,.5]),head=mesh(geo.sphere,skinM,[0,2.35,0],[.42,.48,.42]);runner.add(body,head);head.add(mesh(geo.box,hairM,[0,.25,-.04],[.88,.25,.9]));head.add(mesh(geo.box,mats.cyan,[0,.02,-.4],[.55,.16,.08]));const scarf=mesh(geo.box,mats.yellow,[0,1.92,.2],[.75,.15,.65]);runner.add(scarf);
const limbs={};function limb(name,x,y,m,scale){let pivot=new THREE.Group();pivot.position.set(x,y,0);let part=mesh(geo.cyl,m,[0,-scale[1]/2,0],scale);pivot.add(part);runner.add(pivot);limbs[name]=pivot}limb('la',-.52,1.75,mats.orange,[.13,.72,.13]);limb('ra',.52,1.75,mats.orange,[.13,.72,.13]);limb('ll',-.27,1.02,mats.dark,[.18,.95,.18]);limb('rl',.27,1.02,mats.dark,[.18,.95,.18]);limbs.ll.children[0].add(mesh(geo.box,mats.cyan,[0,-.48,-.12],[.35,.16,.62]));limbs.rl.children[0].add(mesh(geo.box,mats.cyan,[0,-.48,-.12],[.35,.16,.62]));const shieldBubble=new THREE.Mesh(new THREE.SphereGeometry(1.3,20,12),new THREE.MeshBasicMaterial({color:0x50efff,transparent:true,opacity:.16,side:THREE.DoubleSide}));shieldBubble.position.y=1.25;shieldBubble.visible=false;runner.add(shieldBubble);

const entities=new THREE.Group();scene.add(entities);let objects=[],spawnZ=-105,pattern=0;
function entity(type,lane,z,y=0){let g=new THREE.Group();g.position.set(lane*3,y,z);g.userData={type,lane,hit:false,collected:false};if(type==='coin'){let c=mesh(geo.coin,mats.yellow,[0,.75,0]);c.rotation.z=Math.PI/2;c.add(mesh(geo.torus,mats.yellow,[0,0,0],[.48,.48,.48]));g.add(c)}else if(type==='low'){g.add(mesh(geo.box,mats.orange,[0,.65,0],[2.2,1.15,.45]));g.add(mesh(geo.box,mats.white,[0,.7,-.24],[1.6,.18,.03]))}else if(type==='high'){g.add(mesh(geo.box,mats.dark,[0,2.25,0],[2.4,.75,.55]));[-.9,.9].forEach(x=>g.add(mesh(geo.box,mats.yellow,[x,1.15,0],[.16,2.3,.16])))}else if(type==='train'||type==='moving'){g.add(mesh(geo.box,mats.orange,[0,1.5,0],[2.5,3,8]));g.add(mesh(geo.box,mats.dark,[0,3.08,0],[2.55,.22,8.1]));for(let zz=-2.5;zz<3;zz+=2)g.add(mesh(geo.box,mats.glass,[0,1.85,zz-4.03],[1.6,.65,.05]));g.userData.moving=type==='moving'}else if(type==='ramp'){let r=mesh(geo.box,mats.cyan,[0,.7,0],[2.4,.25,5]);r.rotation.x=-.25;g.add(r);g.userData.ramp=true}else{const colors={magnet:mats.pink,flight:mats.cyan,jump:mats.green,boost:mats.yellow,shield:mats.glass};g.add(mesh(geo.sphere,colors[type],[0,1,0],[.55,.55,.55]));g.add(mesh(geo.torus,colors[type],[0,1,0]));g.userData.power=true}entities.add(g);objects.push(g);return g}
function coinTrail(lane,z,count=7,arc=false,y=0){for(let i=0;i<count;i++)entity('coin',lane,z-i*1.7,y+(arc?Math.sin(i/(count-1)*Math.PI)*2.2:0))}
function generate(){while(spawnZ>-150){pattern++;let d=Math.max(9,15-run.difficulty*.25);spawnZ-=d;let safe=(Math.random()*3|0)-1,kind=pattern%9;
 if(kind===0){[-1,0,1].filter(x=>x!==safe).forEach(x=>entity('train',x,spawnZ));coinTrail(safe,spawnZ+2,6)}
 else if(kind===1){let l=(Math.random()*3|0)-1;entity('low',l,spawnZ);coinTrail(l,spawnZ+2,7,true)}
 else if(kind===2){let l=(Math.random()*3|0)-1;entity('high',l,spawnZ);coinTrail(l,spawnZ+2,6)}
 else if(kind===3&&run.difficulty>3){entity('moving',-safe,spawnZ);coinTrail(safe,spawnZ+2,6)}
 else if(kind===4){let l=(Math.random()*3|0)-1;entity('ramp',l,spawnZ);coinTrail(l,spawnZ-2,7,false,3.3)}
 else if(kind===5){for(let i=0;i<8;i++)entity('coin',((i%3)-1),spawnZ-i*1.5)}
 else if(kind===6){entity(['magnet','flight','jump','boost','shield'][Math.random()*5|0],safe,spawnZ);coinTrail(safe,spawnZ-2,5)}
 else{entity(Math.random()>.5?'low':'high',-safe,spawnZ);coinTrail(safe,spawnZ+1,6)}
 }}

const run={active:false,over:false,paused:false,lane:0,x:0,y:0,vy:0,rolling:0,speed:14,distance:0,coins:0,score:0,mult:1,difficulty:0,stumble:0,powers:{},jumps:0,rolls:0,powerCount:0};
function resetRun(){Object.assign(run,{active:true,over:false,paused:false,lane:0,x:0,y:0,vy:0,rolling:0,speed:14,distance:0,coins:0,score:0,mult:1,difficulty:0,stumble:0,powers:{},jumps:0,rolls:0,powerCount:0});objects.forEach(o=>entities.remove(o));objects=[];spawnZ=-55;pattern=0;generate();runner.visible=true;runner.scale.setScalar(1);shieldBubble.visible=false}
function act(a){if(!run.active||run.paused)return;if(a==='left')run.lane=Math.max(-1,run.lane-1);if(a==='right')run.lane=Math.min(1,run.lane+1);if(a==='jump'&&run.y<.08){run.vy=run.powers.jump?12.2:9.2;run.jumps++;beep(320,.12,'square',.14,650)}if(a==='roll'&&!run.rolling){run.rolling=.72;run.rolls++;beep(180,.13,'sawtooth',.11,90)}}
addEventListener('keydown',e=>{let a={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'jump',w:'jump',W:'jump',' ':'jump',ArrowDown:'roll',s:'roll',S:'roll'}[e.key];if(a){e.preventDefault();act(a)}});
let touch;renderer.domElement.addEventListener('pointerdown',e=>touch={x:e.clientX,y:e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(!touch)return;let dx=e.clientX-touch.x,dy=e.clientY-touch.y;if(Math.max(Math.abs(dx),Math.abs(dy))>24)act(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'roll':'jump'));touch=null});

function toast(t,c='#fff'){let el=$('#toast');el.textContent=t;el.style.color=c;el.style.opacity=1;clearTimeout(el.t);el.t=setTimeout(()=>el.style.opacity=0,700)}
function particles(x,y,color){const cv=$('#fx'),ctx=cv.getContext('2d');let ps=Array.from({length:10},()=>({x,y,vx:(Math.random()-.5)*7,vy:(Math.random()-1)*7,a:1}));function f(){ctx.clearRect(0,0,cv.width,cv.height);ps.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.3;p.a-=.06;ctx.globalAlpha=Math.max(0,p.a);ctx.fillStyle=color;ctx.fillRect(p.x,p.y,4,4)});ctx.globalAlpha=1;if(ps[0].a>0)requestAnimationFrame(f)}f()}
const durations={magnet:7,flight:6,jump:8,boost:8,shield:999};
function power(type){let lv=save.upgrades[type]||0;run.powers[type]=(type==='shield'?999:durations[type]+lv*1.5);run.powerCount++;shieldBubble.visible=!!run.powers.shield;toast(type.toUpperCase()+'!', '#35f4ff');beep(350,.3,'sine',.25,1000)}
function collide(o){let t=o.userData.type;if(o.userData.hit)return;o.userData.hit=true;if(t==='coin'){o.userData.collected=true;run.coins++;run.score+=25*run.mult;beep(720,.05,'sine',.12,1050);return}if(o.userData.power){o.userData.collected=true;power(t);return}if(t==='ramp'){if(run.y<.4){run.vy=7;toast('ROOF ROUTE!');}return}let safe=false;if(t==='low')safe=run.y>1.15;if(t==='high')safe=run.rolling>.05||run.y>3.3;if((t==='train'||t==='moving')&&run.y>3.05)safe=true;if(safe)return;if(run.powers.shield){delete run.powers.shield;shieldBubble.visible=false;run.stumble=.45;toast('SHIELD BREAK!','#ffd43b');beep(170,.3,'sawtooth',.25,60);shake=.25;return}let side=Math.abs(run.x-o.position.x)>.62;if(side){run.stumble=.7;run.speed*=.7;toast('STUMBLE!','#ff9c3c');beep(120,.25,'square',.2,70);shake=.18}else endRun()}
function endRun(){run.active=false;run.over=true;shake=.55;beep(90,.6,'sawtooth',.3,35);save.coins+=run.coins;save.best=Math.max(save.best,Math.floor(run.score));save.totalDistance+=Math.floor(run.distance);save.missions.coins+=run.coins;save.missions.jumps+=run.jumps;save.missions.rolls+=run.rolls;save.missions.distance+=Math.floor(run.distance);save.missions.powers+=run.powerCount;save.missions.mult=Math.max(save.missions.mult,run.mult);persist();setTimeout(()=>{$('#hud').classList.add('hidden');$('#gameover').classList.remove('hidden');$('#finalScore').textContent=Math.floor(run.score).toLocaleString();$('#finalDistance').textContent=Math.floor(run.distance)+' m';$('#finalCoins').textContent=run.coins;$('#finalBest').textContent=save.best.toLocaleString();$('#missionRecap').textContent=`This run: ${run.jumps} jumps · ${run.rolls} slides · ${run.powerCount} power-ups`;refreshMenu()},600)}

let shake=0,clock=new THREE.Clock(),menuTime=0;
function update(dt){menuTime+=dt;if(!run.active){runner.position.set(Math.sin(menuTime*.6)*2.2,0,-3);runner.rotation.y=Math.sin(menuTime*.5)*.18;animateRunner(menuTime,0,false);return}if(run.paused)return;run.difficulty=Math.min(20,run.distance/150);run.speed=lerp(run.speed,14+run.difficulty*.72,dt*.35);if(run.stumble>0)run.stumble-=dt;run.distance+=run.speed*dt*.33;run.mult=Math.min(10,1+Math.floor(run.distance/220));run.score+=run.speed*dt*run.mult;run.x=lerp(run.x,run.lane*3,1-Math.exp(-dt*13));run.vy-=24*dt;run.y+=run.vy*dt;if(run.y<0){if(run.vy<-7){shake=.09;beep(90,.05,'sine',.08)}run.y=0;run.vy=0}run.rolling=Math.max(0,run.rolling-dt);
 runner.position.set(run.x,run.y,0);runner.scale.y=lerp(runner.scale.y,run.rolling?.55:1,dt*18);runner.scale.x=lerp(runner.scale.x,run.rolling?1.2:1,dt*18);animateRunner(menuTime,run.speed,run.rolling>0);
 segments.forEach(s=>{s.position.z+=run.speed*dt;if(s.position.z>SEG){s.position.z-=SEG*COUNT;s.userData.index+=COUNT}});
 spawnZ+=run.speed*dt;objects.forEach(o=>{o.position.z+=run.speed*dt;if(o.userData.moving)o.position.z+=run.speed*.35*dt;if(o.userData.type==='coin'){o.rotation.y+=dt*5;o.position.y+=Math.sin(menuTime*5+o.position.z)*.003;if(run.powers.magnet&&Math.abs(o.position.z)<8&&!o.userData.collected){o.position.x=lerp(o.position.x,run.x,dt*5);o.position.z=lerp(o.position.z,0,dt*4)}}if(o.userData.power)o.rotation.y+=dt*2;if(!o.userData.hit&&Math.abs(o.position.z)<.7&&Math.abs(o.position.x-run.x)<1.05)collide(o)});objects=objects.filter(o=>{if(o.userData.collected||o.position.z>12){entities.remove(o);return false}return true});generate();
 Object.keys(run.powers).forEach(k=>{if(k!=='shield'){run.powers[k]-=dt;if(run.powers[k]<=0)delete run.powers[k]}});if(run.powers.flight){run.y=lerp(run.y,7,dt*3);run.vy=0}updateHud();}
function animateRunner(t,speed,roll){let f=Math.sin(t*(speed?speed*.72:4));limbs.la.rotation.x=f*.8;limbs.ra.rotation.x=-f*.8;limbs.ll.rotation.x=-f*.7;limbs.rl.rotation.x=f*.7;body.rotation.z=Math.sin(t*speed*.35)*.035;if(run.active&&run.y>.15){limbs.la.rotation.x=-.6;limbs.ra.rotation.x=.6;limbs.ll.rotation.x=.4;limbs.rl.rotation.x=-.35}if(roll){limbs.la.rotation.x=1;limbs.ra.rotation.x=1;runner.rotation.x=lerp(runner.rotation.x,-.18,.2)}else runner.rotation.x=lerp(runner.rotation.x,0,.2);scarf.rotation.x=.3+Math.sin(t*7)*.08;shieldBubble.rotation.y+=.02}
function updateCamera(dt){let active=run.active,targetX=active?run.x*.45:0,targetY=active?5.2+run.y*.18:4.5,targetZ=active?8.7:8;camera.position.x=lerp(camera.position.x,targetX,1-Math.exp(-dt*5));camera.position.y=lerp(camera.position.y,targetY,1-Math.exp(-dt*4));camera.position.z=lerp(camera.position.z,targetZ,dt*4);if(shake>0){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;shake-=dt}camera.fov=lerp(camera.fov,active?62+(run.speed-14)*.55:58,dt*2);camera.updateProjectionMatrix();camera.lookAt(active?run.x*.25:0,active?1.25+run.y*.15:1.4,-6)}
function updateHud(){$('#score').textContent=Math.floor(run.score).toLocaleString();$('#coins').textContent=run.coins;$('#multiplier').textContent=run.mult;$('#powerHud').innerHTML=Object.keys(run.powers).map(k=>`<div class="power"><b>${k.toUpperCase()}</b>${k==='shield'?' READY':` ${run.powers[k].toFixed(1)}s`}<i style="width:${k==='shield'?100:Math.min(100,run.powers[k]/(durations[k]+(save.upgrades[k]||0)*1.5)*100)}%"></i></div>`).join('')}
function loop(){let dt=Math.min(.033,clock.getDelta());update(dt);updateCamera(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}camera.position.set(0,5,9);loop();

const missionDefs=[['coins','Collect 100 coins',100,250],['jumps','Jump 20 times',20,150],['rolls','Slide 15 times',15,150],['distance','Run 1,000 meters',1000,300],['powers','Use 3 power-ups',3,200],['mult','Reach ×5 multiplier',5,250]];
function refreshMenu(){$('#bankCoins').textContent=save.coins;$('#bestScore').textContent=save.best.toLocaleString()}
function showPanel(type){$('#panel').classList.remove('hidden');let title='',html='';if(type==='shop'){title='POWER LAB';html='<div class="shop-grid">'+Object.entries({magnet:'🧲 Magnet',flight:'🚀 Flight',jump:'⚡ Super Jump',boost:'✦ Score Boost',shield:'◈ Shield'}).map(([k,n])=>{let lv=save.upgrades[k],cost=150*(lv+1);return `<div class="shop-item"><span class="icon">${n.split(' ')[0]}</span><div><b>${n.slice(2)}</b><small>Level ${lv} · ${k==='shield'?'Impact recharge':'+'+(lv*1.5).toFixed(1)+'s duration'}</small></div><button data-buy="${k}" ${save.coins<cost?'disabled':''}>◉ ${cost}</button></div>`}).join('')+'</div>'}else if(type==='missions'){title='MISSIONS';html='<div class="mission-list">'+missionDefs.map(([k,n,max,reward])=>{let v=Math.min(max,save.missions[k]),done=v>=max,claimed=save.claimed[k];return `<div class="mission"><div style="flex:1"><b>${n}</b><small>${v} / ${max} · Reward ◉ ${reward}</small><div class="bar"><i style="width:${v/max*100}%"></i></div></div>${done&&!claimed?`<button data-claim="${k}">CLAIM</button>`:claimed?'✓':''}</div>`}).join('')+'</div>'}else if(type==='characters'){title='RUNNERS';html='<p>Choose your street style.</p><div class="shop-grid">'+[['Volt','Neon courier'],['Ember','Sunset sprinter'],['Mint','Skyline scout']].map((x,i)=>`<button class="skin ${save.skin===i?'selected':''}" data-skin="${i}"><b>${x[0]}</b><small>${x[1]}</small></button>`).join('')+'</div>'}else{title='SETTINGS';html=`<button data-toggle="music">Music: ${save.music?'ON':'OFF'}</button><button data-toggle="sfx">Sound FX: ${save.sfx?'ON':'OFF'}</button><p><small>Progress is saved automatically on this device.<br>Use keyboard or swipe in any direction.</small></p>`}$('#panelTitle').textContent=title;$('#panelBody').innerHTML=html}
function hide(...ids){ids.forEach(id=>$(id).classList.add('hidden'))}
function start(){audio();music(true);resetRun();hide('#menu','#gameover','#panel');$('#hud').classList.remove('hidden');toast('READY — GO!','#ffd43b')}
function menu(){run.active=false;music(false);hide('#gameover','#hud','#panel');$('#menu').classList.remove('hidden');refreshMenu()}
document.addEventListener('click',e=>{let a=e.target.closest('[data-action]')?.dataset.action,p=e.target.closest('[data-panel]')?.dataset.panel,b=e.target.closest('[data-buy]')?.dataset.buy,c=e.target.closest('[data-claim]')?.dataset.claim,s=e.target.closest('[data-skin]')?.dataset.skin,t=e.target.closest('[data-toggle]')?.dataset.toggle;if(a==='play')start();if(a==='menu')menu();if(a==='close')$('#panel').classList.add('hidden');if(p)showPanel(p);if(b){let cost=150*(save.upgrades[b]+1);if(save.coins>=cost){save.coins-=cost;save.upgrades[b]++;persist();showPanel('shop');refreshMenu();beep(600,.15)}}if(c){let def=missionDefs.find(x=>x[0]===c);save.coins+=def[3];save.claimed[c]=true;persist();showPanel('missions');refreshMenu()}if(s!=null){save.skin=+s;body.material=[mats.pink,mats.orange,mats.green][save.skin];persist();showPanel('characters')}if(t){save[t]=!save[t];persist();if(t==='music')music(save.music);showPanel('settings')}});$('#pause').onclick=()=>{run.paused=!run.paused;toast(run.paused?'PAUSED':'GO!')};
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);$('#fx').width=innerWidth;$('#fx').height=innerHeight}addEventListener('resize',resize);resize();refreshMenu();
